services:
  - type: web
    name: school_app
    env: nixpacks
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:$PORT login.php"
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
